### ISSUE TITLE
Segfault when selecting Ultra-VNC

### ISSUE THREAD

**Issue by iak92** [muflone/remmina-plugin-ultravnc#2]
I've installed Remmina, ultravnc-viewer, rdp and uvnc plugin. When I select UltraVNC form the dropdown menu Remmina crashes with a Segfault.
Using Arch-Linux

**Comment by muflone** [comment]
fixed in 1.3.0.0
in the next hours I'll publish an update for the AUR package

**Comment by muflone** [comment]
The package remmina-plugin-ultravnc was updated on AUR
