### ISSUE TITLE
CMakeLists.txt error

### ISSUE THREAD

**Issue by cutix65** [muflone/remmina-plugin-ultravnc#3]
Hello !
When I launch the command cp --recursive remmina-plugin-ultravnc CMakeLists.txt remmina-plugin-builder-1.3.0.0/remmina-plugin-to-build/ I get an error since CMakeLists.txt doesn't exist. I tired several times, no way. Can you pls help ?
Thanks

**Comment by muflone** [comment]
Hi
Describe exactly all the steps involved and the whole output

**Comment by cutix65** [comment]
Ok, I launch the firts 2 commands

wget -O remmina-plugin-builder.tar.gz https://github.com/muflone/remmina-plugin-builder/archive/1.3.0.0.tar.gz
tar --extract --verbose --gzip --file remmina-plugin-builder.tar.gz

and I get the direcory remmina-plugin-builder-1.3.0.0, fine

When you get, similarly, the remmin-plugin-ultravnc direcry, you said to launch this command:
cp --recursive remmina-plugin-ultravnc CMakeLists.txt remmina-plugin-builder-1.3.0.0/remmina-plugin-to-build/

I do it withing my master directory, the one that hosts both directories remmina-plugin-ultravnc and remmina-plugin-builder-1.3.0.0 The fact is...CMakeLists.txt that is mentioned into your command, from my perspective, is missing as in fact the cp command fails with this: "cp: cannot stat 'CMakeLists.txt': No such file or directory"

Where am I wrong ?
Thanks

**Comment by muflone** [comment]
the file CMakeLists.txt is in the project root:

https://github.com/muflone/remmina-plugin-ultravnc, if you don't have it you haven't downloaded the project files

Maybe you downloaded an archive to decompress, containing both?

**Comment by cutix65** [comment]
Correct. Now it works, my error. Thanks !
